### PR TITLE
Added How to use traducir.win

### LINKED ISSUE #89: Help! (I mean what about the docs for end-users)
Thanks to Pikoh I recently learned about the use of "Mark as urgent" but knowing me it's very like that I will forget what I learned (shame on me).

It's it OK to make a PR to add a Help section to the readme.md for non-so-pretty-obvious things?

### PR DESCRIPTION
**Pull request by rubenrivera**
Added a pretty brief user guide named How to use traducir.win.

Fixes #89

### CODE REVIEW

**Comment by topcatarg** [comment]
Altough is fine to have this in a readme.. maybe it's better to have this as a page on the app?? altough we can have both versions

**Comment by g3rv4** [comment]
I'd say:

1. Create a new page inside of [/docs](https://github.com/g3rv4/Traducir/tree/master/docs)
2. Add a link to it on the README.md
3. We can also add a link on the app itself to the doc (as we're doing on the db instructions)

makes sense?

**Comment by topcatarg** [comment]
That sounds better..

**Comment by rubenrivera** [comment]
I created /docs/TOUR.md and updated my README.md from my first commit. Later we could create detailed help articles perhaps on /docs/help.

**Pull request merged**
